# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DemoResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('careerko', models.TextField()),
                ('careeren', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='patent',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='notice',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='news',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='member',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='lecturevideo',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='greeting',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='demoresource',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='community',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='about',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
    ]
