# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DemoResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('careerko', models.TextField()),
                ('careeren', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameko', models.CharField(max_length=100)),
                ('nameen', models.CharField(max_length=100)),
                ('positionko', models.CharField(max_length=100)),
                ('positionen', models.CharField(max_length=100)),
                ('departmentko', models.TextField()),
                ('departmenten', models.TextField()),
                ('educationko', models.TextField()),
                ('educationen', models.TextField()),
                ('careerko', models.TextField()),
                ('careeren', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='submenu',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='report',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='publication',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='project',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='patent',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='notice',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='news',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='member',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='lecturevideo',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='lab',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='greeting',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='demoresource',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='community',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubMenu'),
        ),
    ]
