# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_member_testimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='testImage',
        ),
    ]
